# Generated by Django 2.2.7 on 2019-11-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
